name: GitHub Actions Build and Deploy Demo
on:
  create:
    tags:
      - v*

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: source

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
    - run: pip install -r requirements.txt

    - name: Build
      run: pyinstaller app-onefile.spec

    - name: Copy resource
      run: |
        mkdir .\dist\resource\
        xcopy .\resource\ .\dist\resource\ /E
        xcopy .\config.json .\dist\ /E

    - name: Zip Release
      uses: TheDoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'release.zip'
        directory: 'dist'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./dist/release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}